### ISSUE TITLE
Credentials for Sonatype warning

### ISSUE THREAD

**Issue by xevix** [lloydmeta/scala-akka-cv-part2#1]
Getting this when running sbt.

```
[info] Resolving com.beachape#sbt-opencv;1.5 ...
[error] Unable to find credentials for [Sonatype Nexus Repository Manager @ oss.sonatype.org].
[info] Resolving com.beachape#sbt-javacpp;1.3 ...
[error] Unable to find credentials for [Sonatype Nexus Repository Manager @ oss.sonatype.org].
```

**Comment by lloydmeta** [comment]
Odd. Are these warnings and you can still run the project or are they errors that stop all the things.

**Comment by xevix** [comment]
Although it says "error" sbt keeps going and running it works fine. Looking at `project/plugins.sbt` I notice that staging of Sonatype is being used. Does that generally ask for credentials?

**Comment by lloydmeta** [comment]
Interesting. Yeah, I had that there so it would resolve plugins that I haven't committed to publishing yet (semi-testing on prod...). Does the project work if you remove it?

As far as I know, It shouldn't ask for credentials if you aren't publishing anything to the repo though.

**Comment by xevix** [comment]
Yep, commenting it out makes the "errors" go away. To reproduce, I clear out those 2 packages from my Ivy cache then run sbt again.

**Comment by lloydmeta** [comment]
I see. I'll delete that line and commit it then.

**Comment by lloydmeta** [comment]
Done.
